name: macos-build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        env:
          CC: clang-10
          CXX: clang++-10
        run: |
          ./build.sh
      - name: test
        run: |
          ./test.sh
