name: macos-build

on:
  push:
    paths:
    - examples/**
    - phreesqlib/**
    - phreesqlexe/**
    - external/**
    - .github/workflows/macos.yml
    - build.sh
    - test.sh

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: dependencies
        run: |
          brew install sqlite3
      - name: build
        env:
          CC: clang
          CXX: clang++
        run: |
          ./build.sh
          ls build/proj/lib
      - name: test
        run: |
          ./test.sh
